### ISSUE TITLE
Turning events into a time series stream

### ISSUE THREAD

**Issue by MovieStoreGuy** [signalfx/signalflow-library#11]
What I am currently trying to do is convert an event (or denote when an event happened) as a boolean time series.

Is this currently possible with existing signalflow?

**Comment by joe-sfx** [comment]
SignalFlow is the API for specifying a computation on metric time series (not events). However, if you are emitting events as time series (describe events with dimensions/properties, value "1" means it happened), then it's possible to mix events and metrics. For example, you can condition a metric alert on the (non-)occurrence of some event(s), or calculate the time between events. Just beware this is not exactly what the system was designed for, and you may run into some sharp edges (concerns around resolution, missing data, active/inactive time series). Please reach out to support if needed.

**Comment by MovieStoreGuy** [comment]
Interesting :) thank you @joe-sfx,

Basically, I'd like to take the `detect` series of event time series to a boolean series which would be _is there an event at this time or not_.

Do you think there is any magic voodoo I could do to resolve this or think this is probably best going to support?

**Comment by joe-sfx** [comment]
That's possible! Use the [when function](https://developers.signalfx.com/signalflow_analytics/functions/when_function.html).

That function creates a boolean stream (which can be assigned, manipulated, combined with other streams, etc.). Also useful in this context might be [map] (https://developers.signalfx.com/signalflow_analytics/methods/map_stream_method.html); branching logic on streams (e.g. `s = t if u > 0 else v` for streams `s, t, u, v`), which can involve `when` blocks as well; and the `and`, `not`, `or` operators on boolean streams (useful for compound alert conditions).
