### ISSUE TITLE
Question: Is it possible to use/add/write third party modules for SignalFX/SignalFlow?

### ISSUE THREAD

**Issue by PatrickShaw** [signalfx/signalflow-library#13]
**Note**: I know this is probably not the right place to ask, being a question rather than an issue, but this is the only place I've seem `from ... import ...` syntax and `.flow` files being used for SignalFX. Please forgive me ><

Hi,

I stumbled across this repo while trying to look for certain syntax features of SignalFlow. My understanding is that the utilities in this repo can be imported in SignalFX directly into SignalFX's chart's SignalFlow code using `from ... import ...` statements.

I'm wondering, is there any documentation (if it's even possible) to write our own SignalFlow modules/libraries and import them into the SignalFlow code for SignalFX charts?

Hope that makes sense,
Cheers!

**Comment by joe-sfx** [comment]
This is a great place to ask! User-defined modules are not currently supported, but within the context of a single program, the constructions/features used in this library are available to you. I've just added a [document](https://github.com/signalfx/signalflow-library/blob/master/library/signalfx/docs/flow.md) describing some of this functionality, as well as high-level SignalFlow design. Feedback is welcome.

Also, if the utilities/modules you have in mind are generally applicable, we could consider adding them to the library.

**Comment by PatrickShaw** [comment]
Awesome! Thanks so much for getting back to me quickly and for writing such a detailed document - Learnt lots of things about SignalFlow's features from it 😄

The only thing I can think of that might also be worth mentioning is that SignalFlow also supports [**kwargs](https://book.pythontips.com/en/latest/args_and_kwargs.html#usage-of-kwargs) syntax which I've found pretty handy.

I'll close the issue now
